### ISSUE TITLE
OAuth2? 

### ISSUE THREAD

**Issue by trikosuave** [lionheart/python-harvest#22]
Hi. The token shows refresh_token and access_token. Via the Authorized OAuth2 API Clients in harvest I only see client_id and client_secret. Where do I find/create refresh/access tokens to use with this library?

Thanks!

**Comment by memmott** [comment]
PR#19 address this

**Comment by trikosuave** [comment]
Excellent! Thank you!

**Comment by trikosuave** [comment]
Hi. Quick question. I am hoping to write a simple python app that will grab a couple bits of data from Harvest. I want this app to be ran automatically at times and really don't want to use email/password to auth (as that would have to be stored somewhere). I also think it would be a lot of extra work to setup and keep state of a token for Authorization Code Flow. 
Any chance Harvest can or will support Client Credentials Grant to use id/key more directly for a more simple OAuth solution? https://tools.ietf.org/html/rfc6749#section-4.4

Thanks!

**Comment by dlo** [comment]
This project is not maintained by the Harvest team, so you'll need to ask Harvest directly for that. 😀
