### ISSUE TITLE
Refreshed tokens?

### ISSUE THREAD

**Issue by sxalexander** [lionheart/python-harvest#23]
How does one use the updates from #19  to request a new token?  It seems that OAuth2 isn't fully supported if token refresh isn't working.  There's no mention of refreshing token in the Readme.

**Comment by memmott** [comment]
@sxalexander this supports usage with refresh_tokens (mislabelled PR, sorry) & OAuth2 as a wrapper. I am working on integrating something that does the following: also takes in client_secret, then POSTS with necessary post_data (refresh_token, client_id, client_secret, and grant_type) to '/oauth2/token' and returns the json response. Locally, I have a cron job sending the requests which you might consider in the meantime (not sure when this will happen).

**Comment by sxalexander** [comment]
thanks @memmott, I thought perhaps I was missing something.  It sounds like there's not a way to do this currently using the library.  I'll handle it using a `requests` based workflow for now

**Comment by Brad-eki** [comment]
In the move to support Harvest API v2, the authentication paradigm has been refactored. Currently supports two types of OAuth2 flows and in one of them supports refreshing tokens.
