### ISSUE TITLE
I am not able to upload the updated project to pypi

### ISSUE THREAD

**Issue by FlatEarthTruth** [lionheart/python-harvest#28]
```Registering package to https://upload.pypi.org/legacy/
Enter your username: gxela
Enter your password:
Registering python-harvest-redux-2.0.2.tar.gz
HTTPError: 410 Client Error: This API is no longer supported, instead simply upload the file. for url: https://upload.pypi.org/legacy/```

**Comment by benkonrath** [comment]
I think you need to use twine to setup a new project and upload to pypi: https://github.com/dstufft/twine

Are you planning to take over this project? Maybe @lionheart will transfer the project to you. If you're going to do a fork, I can submit my invoices / python 3 PR (#27) to your version.

**Comment by dlo** [comment]
@benkonrath is right--PyPi updated their API. Closing for now.
