### ISSUE TITLE
When using basic auth the authorization header is wrong in Python 3

### ISSUE THREAD

**Issue by maksymilian-majer** [lionheart/python-harvest#33]
The authorization header is set in line 55 like this:
```
self.__headers['Authorization'] = 'Basic {0}'.format(enc64("{self.email}:{self.password}".format(self=self).encode("utf8")))
```

This produces a string like:
`'Basic b\'some_base_64\''`

Instead of:
`'Basic some_base_64'`

This can be simply fixed by calling `.decode()` on the Base64 encoded bytes.

**Comment by dlo** [comment]
Fixed by #34
