### ISSUE TITLE
PyPi Releases are outdated

### ISSUE THREAD

**Issue by bpabel** [lionheart/python-harvest#35]
It looks like this project was being pushed to PyPi at one time, but the releases there are no longer up to date.

**Comment by dlo** [comment]
@bpabel Thanks for filing an issue. Can you clarify?

https://pypi.python.org/pypi/python-harvest-redux is up-to-date.

**Comment by bpabel** [comment]
I was referring to the `python-harvest` package on PyPi -- https://pypi.org/project/python-harvest/1.0.4/

It looks like both packages are owned by the same author.

**Comment by dlo** [comment]
I think ended up misplacing credentials for that package and just released a new package instead. The new package name is in the readme so it's the canonical package now.

**Comment by bpabel** [comment]
It looks like you just need to be added as a Maintainer to the other project.  There's a process to request that from the PyPi admins now.  You can just make a ticket here:

https://sourceforge.net/p/pypi/support-requests/

Given that the project homepages are the same for both projects, I imagine they would quickly add you so you can update the original project.
