### ISSUE TITLE
Harvest API v1 to Harvest API v2

### ISSUE THREAD

**Issue by Brad-eki** [lionheart/python-harvest#37]
Hi,

I'm writing an accounting integration between Harvest and elsewhere. Thanks to @benkonrath for the invoice support and @joseph-levine-fjorge for the personal token work I can do most of what I need.

I have found, however, invoice statuses (Harvest API v1) are now called state (HArvest API v2) and have a different collection of possible values. There are other changes which appear to use a profoundly different model between the two API versions.

I am expecting to work predominantly in Harvest API v2.

At the moment, by way of invoice support and personal access tokens, there is an amount of code which is crossing over. My changes will require a break in backwards compatibility or, more accurately, direct support for API v2.

Is there a considered pathway to support API v2 in python-harvest?

**Comment by dlo** [comment]
@Brad-eki There's no plan at the moment, but my gut reaction is that backwards incompatibility would be OK given that this is a major API update. Thanks for all of your contributions so far!

**Comment by Brad-eki** [comment]
@dlo Thanks for such a swift reply.

Considering that view I'm happy to again raise a pull request for the changes I've made.

Cheers

**Comment by Brad-eki** [comment]
We now have a v2 branch and that change has been accepted.

We can close this one.

Thanks @dlo
