### ISSUE TITLE
Excel toolkit / example code

### ISSUE THREAD

**Issue by Brad-eki** [lionheart/python-harvest#44]
Assuming that Excel is a common enough element in people's experience of integrating accounting systems...

Is there an appetite to include a set of toolkits or some-other-how example code to help people use the python-harvest library in some of the more common Excel+Python situations?

For example:
- methods which can be used in xlwings
-- the fundamental objects can turn up in a worksheet
-- the reports (as found in Harvest) can turn up in a worksheet

- methods which can be used in openpyxl 
-- the fundamental objects can turn up in a worksheet
-- the reports (as found in Harvest) can turn up in a worksheet

- methods which can be used on Excel using win32com
-- the fundamental objects can turn up in a worksheet
-- the reports (as found in Harvest) can turn up in a worksheet

The expression between them is really similar. And there's a heap of really annoying boilerplate to get the columns out of the ordered dict (through dataclasses?) and into Excel rows.

Is this too much maintenance for no real gain?

**Comment by Brad-eki** [comment]
The boilerplate I'm talking about is like this (this example is for xlwings):

    wb = xw.Book.caller()
    sheets = xw.sheets

    new_time_entries = sheets.add(name='Harvest Time Entries', after='Sheet1')

    new_time_entries.range('A1').value = 'notes'
    new_time_entries.range('B1').value = 'locked_reason' 
    ...

    time_entries = harvest.time_entries()

    row_counter = 2
    for time_entry in time_entries.time_entries:
        new_time_entries.range('A%s' % row_counter).value = time_entry.notes
        new_time_entries.range('B%s' % row_counter).value = time_entry.locked_reason
        ...

        row_counter += 1

**Comment by dlo** [comment]
@Brad-eki this looks really cool! I personally haven't needed to write an integration like this yet but I'm 99.9999% certain someone else would be interested in beta testing.

**Comment by Brad-eki** [comment]
I have put a first cut of an xlwings example on the v2_dev branch in a directory called examples/xlwings.

Anyone want to help test the example? (and by proxy the API v2 development..)
