### ISSUE TITLE
Not installable via pip (PyPi)

### ISSUE THREAD

**Issue by mekhami** [lionheart/python-harvest#5]
This is the error received when attempting to install via Pip

https://gist.github.com/mekhami/d8d2a7e774fe704d7daa
Thanks for your help.

**Comment by mekhami** [comment]
The MANIFEST.in file is empty, which causes the VERSION file not to be included.  Please update the file and make sure all relevant files are included in the source distribution and release a new version.

**Comment by gxela** [comment]
I've added VERSION and README to the MANIFEST.in file

**Comment by mekhami** [comment]
Alright please let me know when the updated version is published to PyPi.

**Comment by dlo** [comment]
@mekhami I'll push it up in ~ an hour! Thanks @gxela for the change.

**Comment by mekhami** [comment]
Thanks for the quick action, folks. In case you're interested, I built this tool using your package:
https://github.com/mekhami/Sow

**Comment by dlo** [comment]
Actually @gxela it looks like you're the package owner. I can't upload :)

**Comment by gxela** [comment]
I've fixed this issue, it is now at version 1.0.3, Pypi doesn't allow to reupload the file so i had to upload it as a new version

**Comment by gxela** [comment]
pip install python-harvest
